### ISSUE TITLE
ファイル解析(file parsing)

### ISSUE THREAD

**Issue by yudai-simoma** [rinonaito/miniRT#22]

**Comment by rinonaito** [comment]
### エラーのケース

＜行単位＞

- 引数の数が過多/不足している場合→引数の要素カウント関数作成
- Ambient || Cameraが複数回定義されている場合
- Identifierが大文字の要素（A, C, L）が１度も定義されない場合

＜token単位＞

- 引数が指定のフォーマットの範囲外である場合
    - コンマで区切られたtokenの時、要素数が多い場合
    - 区切られた１つの要素に問題があり場合（数字を求めているのにアルファベットが渡されるなど）
